### ISSUE TITLE
Comparability with Thunderbird 73+

### ISSUE THREAD

**Issue by yamsu** [willsALMANJ/tbkeys#11]
I have been using Dorando keyconfig with Thunderbird 60. I haven't upgraded to TB-68 because that extension is no longer supported. I like what you have done with tbkeys. But I'm hesitant to adopt tbkeys as I'm worried it won't be compatible with TB-73 and beyond. Do you have any idea about future compatibility of tbkeys with Thunderbird.

Great job nonetheless and Thanks.

p.s. It is ridiculous that Mozilla can't incorporate custom user keybindings in all their applications.

**Comment by willsALMANJ** [comment]
No, I don't really know where tbkeys will go with future versions of Thunderbird. To some extent it will depend on my free time when I decide I have to update to Thunderbird 78 (and also on if anyone wants to help with compatibility updates or decides to make their own new similar project that works with Thunderbird 78).

If I were to update tbkeys to work with Thunderbird 78, it would likely be using a WebExtension Experiment to allow the current code to keep running. I think some modification to Thunderbird is needed otherwise, and I don't want to spend time on that unless an approach like that gets some support for the core Thunderbird developers. I tried to start a conversation about that here: https://bugzilla.mozilla.org/show_bug.cgi?id=1591730

**Comment by willsALMANJ** [comment]
Okay, I got curious about what was involved in supporting Thunderbird 78 via a WebExtension experiment and implemented it in #12.

**Comment by willsALMANJ** [comment]
Closed by #12

**Comment by yamsu** [comment]
Great Job!!! Thanks started using tbkeys and have upgraded.
