### ISSUE TITLE
the script intercepts key presses in text search boxes

### ISSUE THREAD

**Issue by rubo77** [willsALMANJ/tbkeys#17]
I got this message by Mehdi A.:

> I use Thunderbird 78.0 x64 on Windows 10 x64 version 2004 and the script intercepts key presses in text search boxes like Quick Filter and about:config page. Also, I cannot invoke a menu item, e.g. alt+f for File menu. (locale is en-us and tbkeys version is 2.0.1.)

I cannot reproduce this in Ubuntu 20.04

**Comment by willsALMANJ** [comment]
I checked just now and I can reproduce this. tbkeys sets up a global key event listener that swallows key events. It has a list of element types for which it allows key events to propagate when they have focus. Thunderbird 78changed the element type for these text boxes.

Likely you couldn't reproduce because you are still using Thunderbird 68.
