### ISSUE TITLE
Add 'd' delete message

### ISSUE THREAD

**Issue by glensc** [willsALMANJ/tbkeys#4]
I coming from https://github.com/trlkly/dorando-keyconfig/issues/30, Thanks for the extension, but could You add `d` hotkey for delete message, it's the only reason I used [dorando-keyconfig](https://github.com/trlkly/dorando-keyconfig)

**Comment by willsALMANJ** [comment]
I hope my answer in #5 helps you get the addon working properly. Then you can modify [this line](https://github.com/willsALMANJ/tbkeys/blob/61621f7ab830ff7357b225f24ab5a60b0a7c0ab1/addon/content/tbkeys.js#L111) to use `d` instead of `#` and re-zip the addon.

I wrote the addon such that it could be configurable, but I don't know if I will find the time to add the UI and storage to let users configure it without modifying the source. It is hard to prioritize working on this addon because it will be obsoleted by the next version of Thunderbird.

**Comment by ftoledo** [comment]
Maybe just load a json file from the profile path with the customized shortcuts that permit any user to set your pref shortcuts

**Comment by willsALMANJ** [comment]
@ftoledo Good idea -- much easier than trying to create a full UI. Please take a look at #7.

**Comment by ftoledo** [comment]
> @ftoledo Good idea -- much easier than trying to create a full UI. Please take a look at #7.

thanks! i will test asap!!!

**Comment by glensc** [comment]
Altho #7 is good/cool/etc, it doesn't change anything for me, I find it easier to understand if I modify the source and repackage .zip. currently have to make .zip anyway manually, as there are no releases in this project.

**Comment by ftoledo** [comment]
@willsALMANJ config via json works great i'm really gratefull
@glensc I agree, releases are good for final use.
I hope that @willsALMANJ can merge the tbkeys.json branch and make a release xpi file. 
I'm developer but do not have thundebird api skills. But feel free to contact me if you think that i can help.

Saludos!

**Comment by willsALMANJ** [comment]
Closing this since I merged in the custom shortcuts PR. I also added a xpi for download since it seems like some people are using tbkeys. I like the workflow of building xpi with custom shortcuts as well -- I tried to keep the add-on as simple as possible so it would be easy to modify.
